### ISSUE TITLE
Crashes on overscroll

### ISSUE THREAD

**Issue by borjaruiz** [blazsolar/HorizontalPicker#46]
My app is crashing when scrolling to the limits (end or to the start). Version 1.1.1.

Logcat is showing this Exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EdgeEffect.onAbsorb(int)' on a null object reference
                                                                                at com.wefika.horizontalpicker.HorizontalPicker.computeScrollX(HorizontalPicker.java:806)
                                                                                at com.wefika.horizontalpicker.HorizontalPicker.computeScroll(HorizontalPicker.java:629)
```

This is how I put HorizontalPicker in the layout:

```
<com.wefika.horizontalpicker.HorizontalPicker
                android:id="@+id/picker"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center_vertical"
                android:marqueeRepeatLimit="-1"
                android:overScrollMode="never"
                android:ellipsize="marquee"
                android:layout_marginLeft="1dp"
                android:layout_marginRight="1dp"
                android:textColor="@android:color/black"
                android:textSize="18dp"
                />
```

And this is how I initialize it in my Activity:

```
String[] values = new String[160+1];
        for (int i = 0; i <= 160; i++) {
            values[i] = String.valueOf(i);
        }

        picker = (HorizontalPicker) findViewById(R.id.picker);
        picker.setOnItemClickedListener(this);
        picker.setOnItemSelectedListener(this);
        picker.setValues(values);
        picker.setSideItems(3);
```

What am I doing wrong?
Thanks in advance

**Comment by blazsolar** [comment]
What version are you using?

**Comment by borjaruiz** [comment]
1.1.1
compile 'com.wefika:horizontal-picker:1.1.1'
