### ISSUE TITLE
Rendering Problems Missing styles. Is the correct theme chosen for this layout?

### ISSUE THREAD

**Issue by kim-montano** [blazsolar/HorizontalPicker#48]
_Failed to find style 'horizontalPickerStyle' in current theme (2 similar errors not shown) Couldn't resolve resource @dimen/textSize (2 similar errors not shown) java.lang.NumberFormatException: Color value '@color/textColor' must start with #   at com.android.layoutlib.bridge.impl.ResourceHelper.getColor(ResourceHelper.java:79)   at android.content.res.BridgeTypedArray.getColorStateList(BridgeTypedArray.java:372)   at com.wefika.horizontalpicker.HorizontalPicker.<init>(HorizontalPicker.java:162)   at com.wefika.horizontalpicker.HorizontalPicker.<init>(HorizontalPicker.java:140)_

I traced the problem on **textColor = a.getColorStateList(R.styleable.HorizontalPicker_android_textColor);**

It says here that R.styleable was already removed: http://stackoverflow.com/questions/1717489/android-hello-gallery-tutorial-r-styleable-cannot-be-resolved

**Comment by computerpoet** [comment]
> Failed to find style 'horizontalPickerStyle' in current theme 

I have the same issue, is this solvable in any way ?

**Comment by c1p81** [comment]
same issue..i can't find a workaround or solution
